services:
  app:
    build: .
    container_name: mapageo-app
    depends_on:
      - rabbitmq
      - mongodb
    ports:
      - "3000:3000"
      - "8080:8080"
    networks:
      - app_network
    command: ["sh", "/usr/src/app/start.sh"]

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Puerto AMQP para RabbitMQ
      - "15672:15672" # Interfaz web de RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - app_network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express
    ports:
      - "8081:8081" # Interfaz web para gestionar MongoDB
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - app_network

volumes:
  mongodb_data:
  rabbitmq_data:

networks:
  app_network:
    driver: bridge
